/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScoreboardRouteImport } from './routes/scoreboard'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as GameRouteImport } from './routes/game'
import { Route as EmuRouteImport } from './routes/emu'
import { Route as AboutRouteImport } from './routes/about'
import { Route as FeedbackRouteImport } from './routes/Feedback'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesPokemonRouteImport } from './routes/games/Pokemon'
import { Route as GamesCardgameRouteImport } from './routes/games/Cardgame'

const ScoreboardRoute = ScoreboardRouteImport.update({
  id: '/scoreboard',
  path: '/scoreboard',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const EmuRoute = EmuRouteImport.update({
  id: '/emu',
  path: '/emu',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/Feedback',
  path: '/Feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesPokemonRoute = GamesPokemonRouteImport.update({
  id: '/games/Pokemon',
  path: '/games/Pokemon',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesCardgameRoute = GamesCardgameRouteImport.update({
  id: '/games/Cardgame',
  path: '/games/Cardgame',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Feedback': typeof FeedbackRoute
  '/about': typeof AboutRoute
  '/emu': typeof EmuRoute
  '/game': typeof GameRoute
  '/quiz': typeof QuizRoute
  '/scoreboard': typeof ScoreboardRoute
  '/games/Cardgame': typeof GamesCardgameRoute
  '/games/Pokemon': typeof GamesPokemonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Feedback': typeof FeedbackRoute
  '/about': typeof AboutRoute
  '/emu': typeof EmuRoute
  '/game': typeof GameRoute
  '/quiz': typeof QuizRoute
  '/scoreboard': typeof ScoreboardRoute
  '/games/Cardgame': typeof GamesCardgameRoute
  '/games/Pokemon': typeof GamesPokemonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Feedback': typeof FeedbackRoute
  '/about': typeof AboutRoute
  '/emu': typeof EmuRoute
  '/game': typeof GameRoute
  '/quiz': typeof QuizRoute
  '/scoreboard': typeof ScoreboardRoute
  '/games/Cardgame': typeof GamesCardgameRoute
  '/games/Pokemon': typeof GamesPokemonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Feedback'
    | '/about'
    | '/emu'
    | '/game'
    | '/quiz'
    | '/scoreboard'
    | '/games/Cardgame'
    | '/games/Pokemon'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Feedback'
    | '/about'
    | '/emu'
    | '/game'
    | '/quiz'
    | '/scoreboard'
    | '/games/Cardgame'
    | '/games/Pokemon'
  id:
    | '__root__'
    | '/'
    | '/Feedback'
    | '/about'
    | '/emu'
    | '/game'
    | '/quiz'
    | '/scoreboard'
    | '/games/Cardgame'
    | '/games/Pokemon'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeedbackRoute: typeof FeedbackRoute
  AboutRoute: typeof AboutRoute
  EmuRoute: typeof EmuRoute
  GameRoute: typeof GameRoute
  QuizRoute: typeof QuizRoute
  ScoreboardRoute: typeof ScoreboardRoute
  GamesCardgameRoute: typeof GamesCardgameRoute
  GamesPokemonRoute: typeof GamesPokemonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scoreboard': {
      id: '/scoreboard'
      path: '/scoreboard'
      fullPath: '/scoreboard'
      preLoaderRoute: typeof ScoreboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emu': {
      id: '/emu'
      path: '/emu'
      fullPath: '/emu'
      preLoaderRoute: typeof EmuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Feedback': {
      id: '/Feedback'
      path: '/Feedback'
      fullPath: '/Feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/Pokemon': {
      id: '/games/Pokemon'
      path: '/games/Pokemon'
      fullPath: '/games/Pokemon'
      preLoaderRoute: typeof GamesPokemonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/Cardgame': {
      id: '/games/Cardgame'
      path: '/games/Cardgame'
      fullPath: '/games/Cardgame'
      preLoaderRoute: typeof GamesCardgameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeedbackRoute: FeedbackRoute,
  AboutRoute: AboutRoute,
  EmuRoute: EmuRoute,
  GameRoute: GameRoute,
  QuizRoute: QuizRoute,
  ScoreboardRoute: ScoreboardRoute,
  GamesCardgameRoute: GamesCardgameRoute,
  GamesPokemonRoute: GamesPokemonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
